### ISSUE TITLE
Tracking Issue: Road to 1.0.0

### ISSUE THREAD

**Issue by edward-shen** [edward-shen/bunbun#1]
Bunbun is in a good place where I think most of the features I've wanted out of a service like this is present. Bumping it to 1.0.0 right now wouldn't be too bad of an idea, but I feel as if there are a few minor features that I _feel_ should be supported before a 1.0.0 is released.

### What should be in 1.0.0
- [x] Ability to support JSON return data for executables—One of the things that's notably missing from bunny1 is the ability to directly return body messages instead of redirecting data. A JSON interface would probably be an extensible, cross-language solution for this.
- [x] A fix for editors that edit via swapping the file rather than writing to it.

### What may be in 1.0.0
- [ ] An actual favicon—Right now bunbun doesn't have any sort of artwork, but having one for 1.0.0 would definitely give a more polished feel.
- [x] Per-route visibility—I think per-route visibility would be awesome,
- [ ] More tests/test coverage—I'm actually pretty confident that my current tests are rather comprehensive, but more can't hurt.

### What won't be in 1.0.0
 - Authentication/Per user authentication—I'm not confident enough nor arrogant enough to try and implement a secure system for user authentication. While I definitely would think that this is cool, I'd at the very least would want someone more familiar to cross-check my work or to help me write support. This also means the following won't be part of 1.0.0:
   - Per-user routes
   - State or session based routes

Of course, this is subject to change, but I really think this would be the minimal requirements for 1.0.0. Anything past updates beyond 1.0.0 would only be if I thought were necessary or if there's more interest in bunbun.
